model_name_or_path: swap-uniba/LLaMAntino-3-ANITA-8B-Inst-DPO-ITA

model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
use_peft: true
lora_r: 16
lora_alpha: 32
lora_dropout: 0.1
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
lora_task_type: CAUSAL_LM

######## 
# Data arguments
########
dataset_name: andrewzamai/KIND_WN_PARALLEL_p1mask
dataset_config: default
dataset_train_split: train
dataset_test_split: validation
system_prompt: "Sei un assistente utile per il riconoscimento di entità nominate (NER). Segui le istruzioni qui sotto per annotare le entità richieste da un testo fornito. Impegnati in un processo di ragionamento approfondito: esamina attentamente le definizioni e le linee guida per guidare l'annotazione, discuti i casi ambigui e risolvi l'assegnazione delle classi confrontando i candidati strettamente correlati. Racchiudi il tuo ragionamento tra i tag <think> e </think>. Infine, restituisci le entità annotate nel formato JSON richiesto, racchiuse tra i tag ```json e ``` . Nulla deve essere restituito al di fuori di questi tag. Ragiona e rispondi in Italiano."
chat_template: "{{- bos_token }}\n{%- if custom_tools is defined %}\n    {%- set tools = custom_tools %}\n{%- endif %}\n{%- if not tools_in_user_message is defined %}\n    {%- set tools_in_user_message = true %}\n{%- endif %}\n{%- if not date_string is defined %}\n    {%- if strftime_now is defined %}\n        {%- set date_string = strftime_now(\"%d %b %Y\") %}\n    {%- else %}\n        {%- set date_string = \"26 Jul 2024\" %}\n    {%- endif %}\n{%- endif %}\n{%- if not tools is defined %}\n    {%- set tools = none %}\n{%- endif %}\n\n{#- This block extracts the system message, so we can slot it into the right place. #}\n{%- if messages[0]['role'] == 'system' %}\n    {%- set system_message = messages[0]['content']|trim %}\n    {%- set messages = messages[1:] %}\n{%- else %}\n    {%- set system_message = \"\" %}\n{%- endif %}\n\n{#- System message #}\n{{- \"<|start_header_id|>system<|end_header_id|>\\n\\n\" }}\n{%- if tools is not none %}\n    {{- \"Environment: ipython\\n\" }}\n{%- endif %}\n{{- \"Cutting Knowledge Date: December 2023\\n\" }}\n{{- \"Today Date: \" + date_string + \"\\n\\n\" }}\n{%- if tools is not none and not tools_in_user_message %}\n    {{- \"You have access to the following functions. To call a function, please respond with JSON for a function call.\" }}\n    {{- 'Respond in the format {\"name\": function name, \"parameters\": dictionary of argument name and its value}.' }}\n    {{- \"Do not use variables.\\n\\n\" }}\n    {%- for t in tools %}\n        {{- t | tojson(indent=4) }}\n        {{- \"\\n\\n\" }}\n    {%- endfor %}\n{%- endif %}\n{{- system_message }}\n{{- \"<|eot_id|>\" }}\n\n{#- Custom tools are passed in a user message with some extra guidance #}\n{%- if tools_in_user_message and not tools is none %}\n    {#- Extract the first user message so we can plug it in here #}\n    {%- if messages | length != 0 %}\n        {%- set first_user_message = messages[0]['content']|trim %}\n        {%- set messages = messages[1:] %}\n    {%- else %}\n        {{- raise_exception(\"Cannot put tools in the first user message when there's no first user message!\") }}\n{%- endif %}\n    {{- '<|start_header_id|>user<|end_header_id|>\\n\\n' -}}\n    {{- \"Given the following functions, please respond with a JSON for a function call \" }}\n    {{- \"with its proper arguments that best answers the given prompt.\\n\\n\" }}\n    {{- 'Respond in the format {\"name\": function name, \"parameters\": dictionary of argument name and its value}.' }}\n    {{- \"Do not use variables.\\n\\n\" }}\n    {%- for t in tools %}\n        {{- t | tojson(indent=4) }}\n        {{- \"\\n\\n\" }}\n    {%- endfor %}\n    {{- first_user_message + \"<|eot_id|>\"}}\n{%- endif %}\n\n{%- for message in messages %}\n    {%- if not (message.role == 'ipython' or message.role == 'tool' or 'tool_calls' in message) %}\n        {{- '<|start_header_id|>' + message['role'] + '<|end_header_id|>\\n\\n'+ message['content'] | trim + '<|eot_id|>' }}\n    {%- elif 'tool_calls' in message %}\n        {%- if not message.tool_calls|length == 1 %}\n            {{- raise_exception(\"This model only supports single tool-calls at once!\") }}\n        {%- endif %}\n        {%- set tool_call = message.tool_calls[0].function %}\n        {{- '<|start_header_id|>assistant<|end_header_id|>\\n\\n' -}}\n        {{- '{\"name\": \"' + tool_call.name + '\", ' }}\n        {{- '\"parameters\": ' }}\n        {{- tool_call.arguments | tojson }}\n        {{- \"}\" }}\n        {{- \"<|eot_id|>\" }}\n    {%- elif message.role == \"tool\" or message.role == \"ipython\" %}\n        {{- \"<|start_header_id|>ipython<|end_header_id|>\\n\\n\" }}\n        {%- if message.content is mapping or message.content is iterable %}\n            {{- message.content | tojson }}\n        {%- else %}\n            {{- message.content }}\n        {%- endif %}\n        {{- \"<|eot_id|>\" }}\n    {%- endif %}\n{%- endfor %}\n{%- if add_generation_prompt %}\n    {{- '<|start_header_id|>assistant<|end_header_id|>\\n\\n<think>\\n' }}\n{%- endif %}\n"

######## 
# GRPOConfig(TrainingArguments)
########
disable_dropout: true
remove_unused_columns: false     
max_prompt_length: 2000          # max txt_report length (up to 2K words) + instruction tokens
max_completion_length: 3000
num_generations: 3               # global batch size (num_processes eg 3gpus * per_device_train_batch_size eg 3) must be divisible by this value
num_iterations: 2                # each prompt can be upsampled to num_generations x num_iterations completions        

mask_truncated_completions: true

temperature: 0.9                 # higher training temperature allows for more completions exploration
top_p: 0.9

beta: 0.005                      # beta for KL divergence loss
epsilon_high: 0.1                # as DAPO paper suggests

#sync_ref_model: true
#ref_model_sync_steps: 30

#> Parameters that control generation acceleration powered by vLLM
# vllm_server_host: $NODE_NAME   # set in grpo.py with os.environ['NODE_NAME'], assigned at runtime
use_vllm: true
vllm_server_port: 2020
vllm_server_timeout: 400

scale_rewards: false              # do not scale advantages by std
log_completions: true             # log completions to wandb 
num_completions_to_print: 1

loss_type: "grpo"  #dr_grpo

reward_funcs:
- format
- microf1_reward
reward_weights:
- 1.0
- 1.0

#> TrainingArguments
resume_from_checkpoint: false   # if true and output_dir contains a valid cp it resumes training from it

bf16: true
bf16_full_eval: true
do_eval: true
eval_strategy: 'no'
save_strategy: steps
save_only_model: false
#eval_steps: 150  # 20 
save_steps: 20   # 10

gradient_accumulation_steps: 64  # 64
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-5
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
#warmup_ratio: 0.05
max_steps: -1

num_train_epochs: 30
output_dir: ./trained_models/Llamantino-8B-GRPO-SLIMERIT-PARALLEL-p1mask-binary-04
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
push_to_hub: false
report_to:
- wandb
seed: 42

# CustomTrainingConfig:
# ---- parameters strictly related to the chosen model ----
pad_token_id: 128004
#---------------------------------------------------------
template_path: "./src/SFT_finetuning/templates"
prediction_prompter: "LLaMA3-chat-NOheaders"